---
title: "Untitled"
author: "Jiacheng Gu"
date: "5/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Read the test set and train set:
```{r}
library(tidyverse)
library(phangorn)
library(phytools)
train <- read.csv("DREAM_data_intMEMOIR_train.csv",stringsAsFactors=FALSE)
test <- read.csv("DREAM_data_intMEMOIR_test.csv",stringsAsFactors=FALSE)
head(test)
```
# 1. Extract parent-child pairs
```{r}
train.bl <- lapply(1:76, function(i) read.csv(sprintf("CBMF4761-final-project-master/Train_csv/%d.csv",i)))
```
Convert BL proportion into exact length:
Combine into one df:

```{r}
train.bl[[1]]$parent <- as.character(train.bl[[1]]$parent)
train.bl[[1]]$child <- as.character(train.bl[[1]]$child)
depth <- nodeheight(all.ground.truth[[1]],node=1)
train.bl[[1]]$pred_len <- train.bl[[1]]$pred_len * depth
x <- train.bl[[1]]
for (i in 2:76){
  # pick parent-child pair that have all the 10 bits
  train.bl[[i]]$parent <- as.character(train.bl[[i]]$parent)
  train.bl[[i]]$child <- as.character(train.bl[[i]]$child)
  depth <- nodeheight(all.ground.truth[[i]],node=1)
  train.bl[[i]]$pred_len <- train.bl[[i]]$pred_len * depth
  x <- rbind(x, train.bl[[i]])
}
# filter out barcodes with < 10 bits
x <- x[(nchar(x$parent)==10)&(nchar(x$child)==10),]
x
```
switch table (parent->child):
p->c: x
1->0: 1
1->2: 2
x= p * c
```{r}
# split into single bit
parent <- matrix(unlist(strsplit(x$parent, '')), ncol = 10, byrow =T)#,      dimnames = list(barcode.set,NULL)
child <- matrix(unlist(strsplit(x$child, '')), ncol = 10, byrow =T)#,      dimnames = list(barcode.set,NULL)
compare <- matrix(0, nrow = nrow(x), ncol = 20)
mut.count <- vector("integer", nrow(x))
count1 <- 0
count2 <- 0
for(i in 1:nrow(x)){
  for(j in 1:10){
    if(parent[i,j]!=child[i,j]){
      p <- switch(parent[i,j], "1"=1, "0"=0, "2"=0)
      c <- switch(child[i,j], "1"=0, "0"=1, "2"=2)
      y <- p*c # which type of change
      #1->0: 1, 1->2: 2
      if(y==1){count1=count1+1}else if(y==2){count2=count2+1}
      if(y>0){compare[i,2*(j-1)+y] <- 1}
    }
  mut.count[[i]] <- count
  }
}
count1/count2 # f(1->0)/f(1->2)
```
summarize type of mut:
```{r}
type.mut <- matrix(0, nrow = 10, ncol = 9)
for(i in 1:nrow(x)){
    for(j in 1:10){
            p <- switch(parent[i,j], "1"=1, "0"=0, "2"=2)
            c <- switch(child[i,j], "0"=0, "1"=1, "2"=2)
            y <- 3*p+c+1 # which type of change
            type.mut[j,y] <- type.mut[j,y]+1
        }
}
colnames(type.mut) <- c('0->0','0->1','0->2','1->0','1->1','1->2','2->0','2->1','2->2')
row.names(type.mut) <- paste('bit',1:10,sep='')
type.mut
# output
write.csv(type.mut, "type_mut.csv")
```
# 2. Get the final RF table
Read ground-truth, basline (rec) and predicted trees:
```{r}
pred.train <- read.csv("final_updated_train_newick.csv",stringsAsFactors=F)
pred.test <- read.csv("final_updated_test_newick.csv",stringsAsFactors=F)
pred.train.adj <- read.csv("final_updated_train_adj_newick.csv",stringsAsFactors=F)
pred.test.adj <- read.csv("final_updated_test_adj_newick.csv",stringsAsFactors=F)
test.gt <- read.newick(text = test$ground)
test.rec <- read.newick(text = test$rec)
test.pred <- read.newick(text=pred.test$x)
test.pred.adj <- read.newick(text = pred.test.adj$x)
```
Get RF:
```{r}
RF.gt.rec <- sapply(1:length(test.gt), function(i) RF.dist(test.gt[[i]], test.rec[[i]], normalize = T))
RF.gt.pred <- sapply(1:length(test.gt), function(i) RF.dist(test.gt[[i]], test.pred[[i]], normalize = T))
RF.gt.pred.adj <- sapply(1:length(test.gt), function(i) RF.dist(test.gt[[i]], test.pred.adj[[i]], normalize = T))
RF.rec.pred <- sapply(1:length(test.gt), function(i) RF.dist(test.pred[[i]], test.rec[[i]], normalize = T))
RF.rec.pred.adj <- sapply(1:length(test.gt), function(i) RF.dist(test.rec[[i]], test.pred.adj[[i]], normalize = T))
test.df <- data.frame(RF.gt.rec,RF.gt.pred, RF.gt.pred.adj, RF.rec.pred, RF.rec.pred.adj)
# convert RF=0 to RF =1 due to the discrepancy in handling the extreme case of identical trees
for(i in 1:5){
  for(j in 1:30){
    if(test.df[j,i]==0){test.df[j,i]<- 2}  # 0-.>2
  }
}
for(i in 1:5){
  for(j in 1:30){
    if(test.df[j,i]==1){test.df[j,i]<- 0} # 1-> 0
  }
}
for(i in 1:5){
  for(j in 1:30){
    if(test.df[j,i]==2){test.df[j,i]<- 1} # 2->1
  }
}
head(test.df)
```
```{r}
plot(test.pred[[5]])
plot(test.gt[[5]])
plot(test.rec[[5]])
plot(test.pred.adj[[5]])
```

```{r}
#train
train.gt <- read.newick(text = train$ground)
train.rec <- read.newick(text = train$rec)
train.pred <- read.newick(text = train$pred)
train.pred.adj <- read.newick(text = train$pred_adj)

RF.gt.rec <- sapply(1:length(train.gt), function(i) RF.dist(train.gt[[i]], train.rec[[i]], normalize = T))
RF.gt.pred <- sapply(1:length(train.gt), function(i) RF.dist(train.gt[[i]], train.pred[[i]], normalize = T))
RF.gt.pred.adj <- sapply(1:length(train.gt), function(i) RF.dist(train.gt[[i]], train.pred.adj[[i]], normalize = T))
RF.rec.pred <- sapply(1:length(train.gt), function(i) RF.dist(train.pred[[i]], train.rec[[i]], normalize = T))
RF.rec.pred.adj <- sapply(1:length(train.gt), function(i) RF.dist(train.rec[[i]], train.pred.adj[[i]], normalize = T))
train.df <- data.frame(RF.gt.rec,RF.gt.pred, RF.gt.pred.adj, RF.rec.pred, RF.rec.pred.adj)
for(i in 1:5){
  for(j in 1:76){
    if(is.na(train.df[j,i])){train.df[j,i]<- 0} # NA->0
  }
}
for(i in 1:5){
  for(j in 1:76){
    if(train.df[j,i]==0){train.df[j,i]<- 2}  # 0-.>2
  }
}
for(i in 1:5){
  for(j in 1:76){
    if(train.df[j,i]==1){train.df[j,i]<- 0} # 1-> 0
  }
}
for(i in 1:5){
  for(j in 1:76){
    if(train.df[j,i]==2){train.df[j,i]<- 1} # 2->1
  }
}
head(train.df)
```
Example tree:
```{r}
RF.dist(test.pred[[3]],test.gt[[3]], normalize = T)
plot(test.pred[[3]])
plot(test.rec[[3]])
plot(test.gt[[3]])
```
Save output:
```{r}
write.csv(train_df, "train_RF.csv")
write.csv(test_df, "test_RF.csv")
```

